### ISSUE TITLE
Multiple errors in as_text

### ISSUE THREAD

**Issue by davegaeddert** [dropseedlabs/config-loader#11]
The main thing here that seems like it could be better is that there are multiple errors for the same line. Any good way to deal with that? The secondary minor thing is the `dict_keys` bit in the last error message, would be nice if it didn't say that.

![image](https://cloud.githubusercontent.com/assets/649496/24484596/9fef3e5c-14c4-11e7-8ed2-4940e647d740.png)

**Comment by paulortman** [comment]
closed by #12
