### ISSUE TITLE
Paul Ortman cannot access repo to push code/PR

### ISSUE THREAD

**Issue by paulortman** [dropseedlabs/config-loader#7]
@davegaeddert I've got a unicode & yaml PR whenever I can push to this repo.

**Comment by davegaeddert** [comment]
Try this: https://github.com/dropseedlabs/config-loader/invitations

I gave you write access but it says "awaiting response"...so you must be able to view it through some other permissions somewhere.

**Comment by davegaeddert** [comment]
Oh yeah, the repo is public.
